{% set name = "omas" %}
{% set version = "0.82.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1abe5fac19ce60a8b27003fc358be6ab5006a45fa1c92685946b99e53a9ff71e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >3.6
    - pip
  run:
    - python >3.6
    - numpy >=1.16.1
    - uncertainties
    - pint
    - netcdf4
    - boto3
    - botocore
    - matplotlib-base
    - pymongo
    - dnspython
    - xmltodict
    - xarray
    - pyro5

about:
  home: https://gafusion.github.io/omas
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Ordered Multidimensional Array Structure
  description: |
    OMAS is a set of Python tools that aim at simplifying the interface
    between third-party codes and the ITER IMAS data storage
    infrastructure. IMAS is a set of codes, an execution framework, a
    data model, a data get/put API, and a data storage infrastructure
    used for manipulating ITER data. The IMAS data model organizes data
    into a hierarchical tree. There data is stored in the leaf nodes, and
    the branches are structures or arrays of structures.
  doc_url: https://gafusion.github.io/omas
  dev_url: https://github.com/gafusion/omas

extra:
  recipe-maintainers:
    - smithsp
    - orso82
