{% set name = "omas" %}
{% set version = "0.31.1" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "5d9700a7b8dabdf92140d68de30845297d6a5282664288ff43cd3f6f18ad7dd8" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  build:
    - python
    - pip
    - uncertainties
  run:
    - boto3
    - botocore
    - matplotlib
    - netcdf4
    - numpy
    - pint
    - python
    - uncertainties
    - xarray

about:
  home: https://gafusion.github.io/omas
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Ordered Multidimensional Array Structure
  description: |
    OMAS is a set of Python tools that aim at simplifying the interface
    between third-party codes and the ITER IMAS data storage
    infrastructure. IMAS is a set of codes, an execution framework, a
    data model, a data get/put API, and a data storage infrastructure
    used for manipulating ITER data. The IMAS data model organizes data
    into a hierarchical tree. There data is stored in the leaf nodes, and
    the branches are structures or arrays of structures.
  doc_url: 'https://gafusion.github.io/omas'
  dev_url: 'https://github.com/gafusion/omas'

extra:
  recipe-maintainers: 
    - smithsp
    - orso82
