travis:
  secure:
    BINSTAR_TOKEN: ONX8+co8/NIvAeRlbhAzi5l5XddYrWACQhQv2yyCf1XrKpaiz4H2cFObxVC8Tj8BxqrPGu6dbbRzVCu1CSZABQ3Y2ULxfk+hzNMCDHfP43mphD095BqumnnetH40eD4PSI7TeaN7IFOnuFYtO8aF5Qr9iNiTyVsCwCZ+nwhrOyh7m39W24Gd541Mv+kHaBbqf2ICktVSIPAgCwzDhcMEW//ya5U7ErEigjDVZPD72l5j20E5pnp3va21BWsJ9Sow9Jm8J3WHJnr/oTDS9K6rwDtxoeGB1Fzm7hrzE1Xn5bIkzqlZeCANw/sUwtFnbYVNZOFmh8NcpoCIicLCitU7MHkothPesQmMD8SF8cWVvh4xXPprbTHbxmLWJEJrVpMwkVyNPQgYmxI1arO535BNa/QjRvqUGAugfPIGDUQQesZ0RvV17YsceAXAYOCZ0mK0Ck9xPFhvbHS4akE8ktkoP1KtCHkxK2LKjE67SypAbfcEZ27SCJtXJvtAS6ZzkVGNfF7E5CEZDOfSs/8t1W/e5A/v2jI475c2xvsoJAquyWfJXP3qKlgFWbdhNoV3K6nFroUnNJ5vt6HFjdkaF62mz/9QWMSyAy8LCtl+Wp37ILYr7uiMmgGlvS4d/NTRftE+UyPxPSiIpJDEg0+1L5wGLgMoh5a7vz2zxjBM3lg1teE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
